string = 'GGCCTAAGACGCCTTTACTTCGCGTGGGTCAAACATGACTAACGAGAGCTCTGGTGCACGGTTGCTTTTCCGAACGCAGCCGCAATAAGCCTACATCTAGTGCCTTATACGTAAGGAAAGCCGGGAGCTCTTCAAGCCACTCAACAGATTAACGGGACGTAACCTCTTCCAACAGATAAGTCGGCATGGTATTCGGACGGACGTCTTACCCCAATGACATCGCAGTACCAGGCCGTTAGGAAATTTAAATCATAATTTCGATAGGACGCAAAGATATAGTGCACAGGTAGAGCATCAGGGTGCAGTGCACTTGATTCATACCGAGTCTTCGCGATTGCCACTTGCGCTAGCCACAGGGTAAGTCGACAGCGCCATACGGGGTGCAGGACTCACTCCTACCTCGAGGGGTACCGTACTTTCGCATCTGAACAAAGGATATTGGTCTGCCGTTCTATTGACCAGTTTATAGCATAGATAGGAAGTTCGTTCGGCCGTCTGGCGGGAAAGCATGCATGAGCCTCGCTTGAGATCGGCTACACCACATGTACATAAGGGGAAGCCAACCACGTGGCTTTCTAGTAAACAAGTGCAGGATCATTGCATCGAGCCTCCAATCCTATCTTAAGTCCAAGTTTCGGTCCACTTCGTCGTGACCAGACCTTTCGCGGGCGTGAAGTACACGTACGAATACCAAGAATGCCTATTCCGAGCTAACGCTCAAACGTGATGGCTAGTCTCGCTATCAAGCCAAAGGATGAACTGTTGTTGGCACGGATTAAACCCTGGGCCAACTAGCAACCAGTACGCGCCGACGTGGATTGGGGACCTGGCAGGGAGCCGCGGTGGCTACCGTCATTTCTGCCGGCAAGAGA'
reverse_string = ''.join(reversed(string))

def rev_complement(seq):
    complement = {'A':'T', 'G':'C', 'C':'G', 'T':'A'}
    rev_comp =''
    for nt in seq:
        rev_comp += complement.get(nt)
    return rev_comp

print(rev_complement(reverse_string))
