main_string = 'GAGTACCCGAGTACCGAGTACCGTGGAATGCACTCAAGAGTACCTGGAGTACCGAGTACCTGACGAGTACCAGCTTTTGAGTACCGAGTACCGAGTACCCCGCGCTAGAGTACCCAGAGTACCATCAGTATGGAGTACCGAGTACCCGGACAGAGTACCTTCGAGTACCGAGTACCGAGTACCCTTCGGAGTACCGGAGTACCTGAGTACCGGAGTACCGAGTACCCAGAGTACCACTGGAGTACCGTAGAGTACCGGAGTACCAAATTATTGATAGTTTGAGTACCTGGAGTACCTGAGTACCTCGGTATGTGCGAGTACCCAACGAGTACCCCAGAGTACCCTTACAGAGTACCAACTTAATGAGTACCTGAGTACCACTCGAGTACCGAGTACCTCGAATCACGGGAGTACCGGAGTACCGAGTACCGAGTACCCAGCGAGTACCATTTGTGAGTACCATTATATTGGAGTACCGTCTTGAGTACCGAGAAGAGTACCATTAGAGTACCCGAGTACCCGCAACAGCTGAGTACCCAGGGAGTACCCGAGTGAGTACCGAGTACCTGAGTACCCGCTTAGAGTACCGGGAGTACCAGGAGTACCGCGTAAGAGGAGTACCTGATCGCGAGTACCCCATCCCTATGAGTACCGTATGGAGTACCGAGTACCGAGTACCCGAGTACCAGAGTACCGGAGTACCGGGAGTACCCAGAGTACCTGTGAGTACCGAGTACCAGGAGTACCCCTTACGAGTACCCTCAGAGTACCAGAGTACCGGTGAGTACCAATATCATGCTCGGGGAGTACCTGAGTACCCGAGTACCGTGGAGTACCGGCTTTGCACCAAAAGAAGCATTAAACGAGTACCGAGTACCGAGTACCGATCGGAGTACCGAGTACC'
substring = 'GAGTACCGA'

def get_loc_subs(str1, str2):
    loc = []
    if len(str2) > len(str1):
        print("Substring bigger than main string")
        return loc
    for i in range(len(str1)-len(str2)+1):
        if str1[i:i+len(str2)] == str2:
            location = i + 1
            loc.append(location)
    return loc

result = ' '.join(map(str,get_loc_subs(main_string,substring)))
print(result)
        